### ISSUE TITLE
VS2022 (Version 17.8.1) can build 

### ISSUE THREAD

**Issue by RobertMassart** [arturbac/fixed_math#1]
after 'Cmake .'  and open and compile from solution get:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2039	'_Countl_zero_fallback': is not a member of 'std'	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	113		
Error	C3861	'_Countl_zero_fallback': identifier not found	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	113		
Error	C3615	constexpr function 'cxx20::countl_zero' cannot result in a constant expression	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	139		
Error	C3615	constexpr function 'cxx20::countl_zero' cannot result in a constant expression	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	140		
Error	C3615	constexpr function 'cxx20::countl_zero' cannot result in a constant expression	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	141		
Error	C3615	constexpr function 'cxx20::countl_zero' cannot result in a constant expression	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	142		
Error	C3615	constexpr function 'cxx20::countl_zero' cannot result in a constant expression	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	143		
Error	C3615	constexpr function 'cxx20::countl_zero' cannot result in a constant expression	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	144		
Warning	C4067	unexpected tokens following preprocessor directive - expected a newline	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	185		
Error	C1189	#error:  "Not bit_cast support at all implement using std::memcpy"	fixed_math	D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h	186

**Comment by arturbac** [comment]
What c++ standard are You using in Your project ?

**Comment by RobertMassart** [comment]
C++17

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RobertMassart** [comment]
I went back to fixed_math-0.9.11 and update the utility_cxx20.h to detect vs2022 C++20 correctly and C++17.

But for latest branch if c++17 you get:

Build started at 9:12 AM...
1>------ Build started: Project: fixed_math, Configuration: Debug x64 ------
1>fixed_math.cc
1>D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h(221,23): warning C4067: unexpected tokens following preprocessor directive - expected a newline
1>(compiling source file 'src/fixed_math.cc')
1>D:\UE5\fixed_math-master\fixed_lib\include\fixedmath\detail\utility_cxx20.h(222,1): error C1189: #error:  "Not bit_cast support at all implement using std::memcpy"
1>(compiling source file 'src/fixed_math.cc')
1>Done building project "fixed_math.vcxproj" -- FAILED.


For latest branch and c++20 I can get it to compile with changes attached (I append _master) so you will know which header applied to master.

**Comment by arturbac** [comment]
Thx.
Yep there were updates for c++20 and c++23 in library side functionalities, which doesn't affect fixed math functions at all.
So You are safe to revert for c++17, You will not lose anything.
I have to find more time to revert partial support for side functions back on msvc with c++17 in master.
Main project at which this lib is used already moved to c++20 that why I missed backward compatibility for msvc c++17.

**Comment by arturbac** [comment]
I fixed master v0.9.17 for using with c++17 masvc, when there is no bitcast support at all it will just not be available and compile with msvc c++17 mode, I can't implement it for msvc c++17 and it is not used in fixedmath at all, it is just side supported function I am using in some project with c++20/17 clang and fixedmath
