### ISSUE TITLE
[BUG] include path is ambiguous

### ISSUE THREAD

**Issue by toge** [arturbac/fixed_math#8]
**Describe the bug**

In examples, the include path is `fixedmath`.
https://github.com/arturbac/fixed_math/blob/v2.0.0/examples/brief-usage.cc#L5-L6

But the include path is `fixed_math`.
https://github.com/arturbac/fixed_math/blob/master/fixed_lib/CMakeLists.txt#L25-L30

Which is valid?

I think `fixedmath` is valid because common.h includes `<fixedmath/detail/type_traits.h>`.
https://github.com/arturbac/fixed_math/blob/v2.0.0/fixed_lib/include/fixedmath/detail/common.h#L8

**Build info:**
 - OS: Fedora Linux 40
 - gcc 14.2.1
 - libstdc++ 14.2.1

**Comment by arturbac** [comment]
Yes, looks like You are right.
I use it by CPM dependency so I do not need to install and did not now about this.
Will asap fix it.
